<?php
/** @var \Comerix\AiAssistant\Block\WidgetScript $block */
/** @var \Magento\Framework\Escaper $escaper */
$widgetUrl = $block->getPpWidgetUrl();
?>
<?php if ($widgetUrl && $block->isEnabled()): ?>
<div id="ai-assistant-additional-container-sidebar" style="margin-top: 16px; margin-bottom: 24px"></div>
<script>
    window.comerixAiConfig = <?= /* @noEscape */ json_encode($block->getWidgetConfig(), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;
</script>
<script src="<?= $escaper->escapeUrl($widgetUrl) ?>"
        data-target="#ai-assistant-additional-container-sidebar"
        data-type="<?= $escaper->escapeUrl($block->getPageType()) ?>"
        async>
</script>
<?php endif; ?>
