<?php
/** @var \Comerix\AiAssistant\Block\WidgetScript $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->isEnabled() && $block->getPpWidgetUrl()): ?>
<div id="ai-assistant-additional-container" style="margin-top: 16px; margin-bottom: 24px"></div>
<script src="<?= $escaper->escapeUrl($block->getPpWidgetUrl()) ?>"
        data-target="#ai-assistant-additional-container"
        data-type="<?= $escaper->escapeUrl($block->getPageType()) ?>"
        async>
</script>
<?php endif; ?>
